# Generated by Django 4.1.7 on 2023-03-15 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_rename_game_city_game_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attendees', to=settings.AUTH_USER_MODEL),
        ),
    ]
